/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TymRouteImport } from './routes/tym'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TymIndexRouteImport } from './routes/tym.index'
import { Route as TymClenRouteImport } from './routes/tym.$clen'

const TymRoute = TymRouteImport.update({
  id: '/tym',
  path: '/tym',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TymIndexRoute = TymIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TymRoute,
} as any)
const TymClenRoute = TymClenRouteImport.update({
  id: '/$clen',
  path: '/$clen',
  getParentRoute: () => TymRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/sluzby': typeof SluzbyRoute
  '/tym': typeof TymRouteWithChildren
  '/tym/$clen': typeof TymClenRoute
  '/tym/': typeof TymIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/sluzby': typeof SluzbyRoute
  '/tym/$clen': typeof TymClenRoute
  '/tym': typeof TymIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/sluzby': typeof SluzbyRoute
  '/tym': typeof TymRouteWithChildren
  '/tym/$clen': typeof TymClenRoute
  '/tym/': typeof TymIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/sluzby' | '/tym' | '/tym/$clen' | '/tym/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/sluzby' | '/tym/$clen' | '/tym'
  id:
    '__root__' | '/' | '/kontakt' | '/sluzby' | '/tym' | '/tym/$clen' | '/tym/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  SluzbyRoute: typeof SluzbyRoute
  TymRoute: typeof TymRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tym': {
      id: '/tym'
      path: '/tym'
      fullPath: '/tym'
      preLoaderRoute: typeof TymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tym/': {
      id: '/tym/'
      path: '/'
      fullPath: '/tym/'
      preLoaderRoute: typeof TymIndexRouteImport
      parentRoute: typeof TymRoute
    }
    '/tym/$clen': {
      id: '/tym/$clen'
      path: '/$clen'
      fullPath: '/tym/$clen'
      preLoaderRoute: typeof TymClenRouteImport
      parentRoute: typeof TymRoute
    }
  }
}

interface TymRouteChildren {
  TymClenRoute: typeof TymClenRoute
  TymIndexRoute: typeof TymIndexRoute
}

const TymRouteChildren: TymRouteChildren = {
  TymClenRoute: TymClenRoute,
  TymIndexRoute: TymIndexRoute,
}

const TymRouteWithChildren = TymRoute._addFileChildren(TymRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  SluzbyRoute: SluzbyRoute,
  TymRoute: TymRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
